# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Upload screenshots and metadata to App Store Connect"
  lane :upload_screenshots_and_metadata do
    # add actions here: https://docs.fastlane.tools/actions
    # deliver (alias for the upload_to_app_store action)
    upload_to_app_store(
      skip_screenshots: false,
      skip_metadata: false,
      skip_binary_upload: true,
      api_key_path: "./fastlane/app_store_connect_api_key.json",
      precheck_include_in_app_purchases: false,
    )
  end
end
