# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Upload screenshots and metadata to Google Play"
  lane :upload_screenshots_and_metadata do
    # add actions here: https://docs.fastlane.tools/actions
    upload_to_play_store(
      skip_upload_metadata: false,
      skip_upload_screenshots: false,
      skip_upload_changelogs: true,
      skip_upload_aab: true,
    )
  end
end